<?php
	require_once("include/respond.php");

	@session_start();

	// include authorization methods
	require_once("include/auth.php");

	if (!isset($_POST["access_token"]) || empty($_POST["access_token"])) {
		http_response_code(400);
		respond("error", "Missing access token");
		die();
	}

	// check if access token was generated by this server
	if (!access_token_accepted($_POST["access_token"])) {
		http_response_code(410);
		respond("error", "Access token was not generated by this server", null);
		die();
	}

	$userInfoFromIntra = get_user_info($_POST["access_token"]);
	if (empty($userInfoFromIntra) || isset($userInfoFromIntra["error"])) {
		http_response_code(410);
		respond("error", "Access token no longer works", $userInfoFromIntra);
		die();
	}
	else {
		http_response_code(200);
		respond("success", "Access token still works", $userInfoFromIntra);
		die();
	}
?>
